import Footer from "./components/footer/page";
import Navbar from "./components/navbar/page";
import "./globals.css";

export const metadata = {
  title: "Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
