import Navbar from "./components/navbar/page";
import "./globals.css";

export const metadata = {
  title: "Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
      <body>{children}</body>
    </html>
  );
}
